version: "3.3"

services:
  identityserver:
    image: robyvandamme/identityserver4-demo
    ports:
      - "8080:80"
  adventureworksdb:
    image: robyvandamme/mssql-server-linux-adventureworks
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
