// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AdminProduct
    {
        /// <summary>
        /// Initializes a new instance of the AdminProduct class.
        /// </summary>
        public AdminProduct()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AdminProduct class.
        /// </summary>
        public AdminProduct(System.Guid? id = default(System.Guid?), string name = default(string), string color = default(string), double? listPrice = default(double?), string productNumber = default(string), string size = default(string), double? weight = default(double?), int? productCategoryId = default(int?), string category = default(string), int? productModelId = default(int?), string model = default(string), byte[] thumbNailPhoto = default(byte[]), string thumbnailPhotoFileName = default(string), double? standardCost = default(double?), System.DateTime? sellStartDate = default(System.DateTime?), System.DateTime? sellEndDate = default(System.DateTime?), System.DateTime? discontinuedDate = default(System.DateTime?), System.DateTime? modifiedDate = default(System.DateTime?))
        {
            Id = id;
            Name = name;
            Color = color;
            ListPrice = listPrice;
            ProductNumber = productNumber;
            Size = size;
            Weight = weight;
            ProductCategoryId = productCategoryId;
            Category = category;
            ProductModelId = productModelId;
            Model = model;
            ThumbNailPhoto = thumbNailPhoto;
            ThumbnailPhotoFileName = thumbnailPhotoFileName;
            StandardCost = standardCost;
            SellStartDate = sellStartDate;
            SellEndDate = sellEndDate;
            DiscontinuedDate = discontinuedDate;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listPrice")]
        public double? ListPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productNumber")]
        public string ProductNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public string Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double? Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productCategoryId")]
        public int? ProductCategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productModelId")]
        public int? ProductModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thumbNailPhoto")]
        public byte[] ThumbNailPhoto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thumbnailPhotoFileName")]
        public string ThumbnailPhotoFileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "standardCost")]
        public double? StandardCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sellStartDate")]
        public System.DateTime? SellStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sellEndDate")]
        public System.DateTime? SellEndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "discontinuedDate")]
        public System.DateTime? DiscontinuedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; set; }

    }
}
