// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ModelError
    {
        /// <summary>
        /// Initializes a new instance of the ModelError class.
        /// </summary>
        public ModelError()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelError class.
        /// </summary>
        public ModelError(object exception = default(object), string errorMessage = default(string))
        {
            Exception = exception;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exception")]
        public object Exception { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; private set; }

    }
}
