// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Product
    {
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product(System.Guid? id = default(System.Guid?), string name = default(string), string color = default(string), double? listPrice = default(double?), string productNumber = default(string), string size = default(string), double? weight = default(double?), int? productCategoryId = default(int?), int? productModelId = default(int?), byte[] thumbNailPhoto = default(byte[]))
        {
            Id = id;
            Name = name;
            Color = color;
            ListPrice = listPrice;
            ProductNumber = productNumber;
            Size = size;
            Weight = weight;
            ProductCategoryId = productCategoryId;
            ProductModelId = productModelId;
            ThumbNailPhoto = thumbNailPhoto;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listPrice")]
        public double? ListPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productNumber")]
        public string ProductNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public string Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double? Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productCategoryId")]
        public int? ProductCategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productModelId")]
        public int? ProductModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thumbNailPhoto")]
        public byte[] ThumbNailPhoto { get; set; }

    }
}
